plot:
    annotations:
        __default__:
            type: "label_repel"
        hg:
            color : "#800000aa"
            size : 4
            pch : "H"
            type : "points"
        bantu:
            color : "#800000aa"
            size : 4
            pch : "B"
            type : "points"
        admixed :
            color : "#800080aa"
            size : 4
            pch : "X"
            type : "points"
    __copy_from__:
        xasia2f : xasia1f
        southafrica0hgP : southafrica0hg
        xasia1frP : xasia1f
        africa3f: africa0fb
        africa2f: africa0fb
        africa0fbP : africa0fb
        eumedi1fP : eumedi1f
        india0fP : india0f
        dindia0 : india0f
        dasia0 : india0f
        dindia0b : india0f
        india1fP : india1f
        xasia1fP : xasia1f
        fasia0f : xasia1f
        seasia0fcP : seasia0fc
        seasia1fcP : seasia0fc
        seasia2fcP : seasia0fc
        global0fgP : global0fg
        global0fh : global0fg    
        india0f: xasia1f
        india1f : india0f
    __default__:
        theme_size : 8
    eems:
        __default__ :
            sign_add_graph : true
            sign_add_pts : true  
            sign_add_pts_color : false
            sign_add_label : true
            fancy : 0
            zoom : 4
            RES : 400
            interior : false
            min_alpha : 0.2
            max_alpha : .7
            add_graph : false
            add_label : false
            fancy_proj_pars : [90, 10, 40]
            do_q_plots : false
            width: 6
            height : 6
            add_pts : false
            add_pts_color : true
            annotations : ['hg', 'admixed']
        eumedi0sb :
            fancy : 1
            fancy_proj_pars : [90, 10, 10]
        eumedi0f :
            sign_add_label : false
            fancy_proj_pars : [90, 10, 10]
            fancy : 1
        xasia0f :
            sign_add_label : false
            fancy : 1
            fancy_proj_pars : [90, 10, 40]
        xasia1f :
            copy : xasia0f
        seasia0fc:
            copy : xasia0f
        seasia0fb:
            copy : seasia0fc
        africa0f :
            copy: xasia0f
        africa1f :
            copy: africa0f
        africa0fb :
            copy: africa0f
            width : 4.7
            height : 4.7
        africa1fb :
            copy: africa0f
        africa0fc :
            copy: africa0f
        global2:
            fancy : 1
            zoom : 3
        global0sm:
            fancy : 1
            zoom : 3
        global1s :
            fancy : 1
        global2s :
            fancy : 1
        global0f :
            fancy : 1
            sign_add_label : false
        global0fb:
            copy : "global0f"
        global0fc:
            copy : "global0f"
        global0fd:
            copy : "global0f"
        global0fe:
            copy : "global0f"
        global0ff:
            copy : "global0f"
        global0fg:
            RES : 400
            add_graph : true
            add_label : true
            add_pts : false
            add_pts_color : false
            width : 24
            height : 24
            copy : "global0f"
        eumedi1f:
            copy : "global0fg"
            width : 15
            height : 15
            sign_add_label : false
            fancy_proj_pars : [90, 10, 10]

        southafrica0f :
            width : 3.5
            height : 3.5
            copy : global0fg
            annotations : ['admix', 'hg']
        southafrica0hg :
            copy : southafrica0f
            annotations : ['bantu', 'admixed']
        southafrica0 : 
            copy : southafrica0f
            annotations : ['bantu', 'admix', 'hg']


        southafrica0s :
            copy : southafrica0f
        global1sf :
            fancy : 1
            #width : 5
            #height : 5
        medi1 :
            fancy : 0
        eumedi0:
            add_graph : false
        southafrica1s:
            width : 2
            height : 2
    synthmap:
        __default__ :
            RES : 400
            fancy_proj_pars : [90, 10, 40]
            width: 4
            height : 4
            idp : 2.5
            pcs: ["PC1", "PC2", "PC3", "PC4"]
    scatter:
        __default__ :
            rsq_size : 2.5
            xvars : ["geoDist", "eems0dist", "eemsdist", "pcDist10"]
            xnames : ["geog.", "resistance", "EEMS-fitted", "PCA-fitted"]
            yvar : ["gendist"]
            point_type : "hex"
            outlier_type : "text"
            outlier_pct : 0.00
            outlier_size : 1.3
            outlier_alpha : .6
            color : "lightgray"
            alpha : .8
            tall : true #whether format should be by row or by col, 
            width : 1
            height : 3
            size : .1
            no_panel : false
        southafrica0hg :
            n_bins : 16
            rsq_size : 4
            xvars : ["geoDist", "eemsdist", "pcDist10"]
            xnames : ["geog.", "EEMS-fitted", "PCA-fitted"]
            tall : true
            width : 2.6
            height : 5
            no_panel : true
            size : 4
        africa0fb:
            no_panel : true
            rsq_size : 2.4
            tall : true
            width : .9
            height : 1.7
            xvars : ["geoDist", "eemsdist", "pcDist10"]
            xnames : ["geog.", "EEMS-fitted", "PCA-fitted"]
        seasia0fc:
            copy : africa0fb
        xasia1f :
            copy : africa0fb
        eumedi1f:
            copy : "southafrica0hg"
            n_bins : 30
            width: 1.2
            height : 2
        southafrica0f: 
            copy : "southafrica0hg"
            n_bins : 15
        southafrica0: 
            copy : "southafrica0hg"
            n_bins : 15
        southafrica0s: 
            copy : "southafrica0hg"
        global0fg: 
            copy : "southafrica0hg"
            n_bins : 30
        _paper_tall :
            tall : true
        _paper_wide :
            tall : false

        seasia3s :
            copy : _paper_tall
            width : .9
            height : 1.6
            no_panel : true
        easia1stest :
            copy : seasia3s
        casia0sd :
            copy : seasia3s

        africa1s:
            copy : _paper_wide
            tall : false
            width : 2.3
            height : .8

        southafrica1s:
            copy : _paper_wide
            tall : false
            width : 2.3
            height : .8
        eumedi1sb:
            copy : _paper_wide
            width : 3
            height : .8
    pve:
        __default__ :
            nmax : 10
            width : 3
            height : 2
    pca2d:
        __default__:
            text_field : "name"
            max_n_pc : 4
            point_type : "text" #points|text|none
            text_size : 1
            point_alpha : 1
            point_grey : true
            median : true
            median_alpha : 1.0
            median_label_grey : false
            median_repel : false
            median_label : true
            median_label_alpha : .8
            median_size : 0.5
            median_label_size : 1.4
            color : "exclusion"
            width : 4
            height : 4
        _paper :
            color: "exclusion"
            median_label_size : 2
            width: 2
            height : 2
            point_type : "points"
            median_label : false
            median_size : 2
            point_alpha : 0.6
            text_size : .5
        _poster:
            color: "location"
            width : 6.5
            height : 6.5
            median_repel : false
            median_size : 1
            median_label_size : 4
            text_size : 3
            theme_size : 18
        southafrica0:
            copy: _poster
            width : 6.5
            height : 4
        eumedi1f:
            copy : _paper
            width : 2.8
            height : 2.2
        europe0f:
            copy : _paper
            width : 2.8
            height : 2.2

        #        europe0f:
            #copy : _poster
            #width : 5
            #height : 5
        southafrica0hg:
            copy : _poster
        africa0fb :
            width: 1.6
            height : 1.8
            copy : _paper
        africa0hg:
            copy : africa0fb
        seasia0fc:
            copy : africa0fb
            width: 1.9
            height : 1.6
        xasia1f :
            copy : africa0fb
            width: 3.5
            height : 2.5
        eumedi1fP:
            copy : africa0fb
            width : 2
            height : 1.5
        global0fg:
            copy : _poster
            median_repel : false
            width : 6.5
            height : 6.5
        global1sf:
            copy : _paper
            point_type : "points"
            median_label : false
            median_size : 2
            point_alpha : 0.6
            text_size : .5
            #width : 2
            #height : 1.7
        seasia3s :
            copy : _paper
            width : 2
            height : 1.2
        easia1s :
            copy : _paper
            width : 2
            height : 1.2
        casia0sd :
            copy : _paper
            width : 2
            height : 1.2
        africa1s:
            copy : _paper
            width : 2.3
            height : 2.3
        southafrica1s:
            copy : _paper
            width : 2.0
            height : 2.0
            median_repel : true
            median_label_size : 2.5
        southafrica0x:
            copy : _paper
            median_repel : true
            median_label_size : 2.5
            text_field : "name"
            width : 3.5
            height : 3.5
        seasia0fb:
            median_repel : true
            text_size : .5
            median_label_size : 3
            point_grey: false
            point_type: "points"
        southafrica0s:
            copy : southafrica0x
        southafrica0f:
            copy: southafrica0x
    error:
        __default__ :
            label : "popId"
            nmax : 50
            grid_label : "first"
            width : 4
            height : 2
        global1sf:
            width : 4
            height : 2
        global2 :
            width : 6
            nmax : 100
        global0s :
            width : 14
            nmax : 300
        global2s :
            copy : "global0s"
            label : "abbrev"
        _poster:
            label : "name"
            nmax : 10
            width : 6
            height : 4
        global0fg:
            copy: _poster
        eumedi1f:
            copy: _poster
        southafrica0:
            copy: _poster
    map :
        __default__ :
            width : 12
            height : 12
            fancy : true
            interior : true

        global0fg:
            width : 20
            height : 20
