channels:
  - conda-forge
  - bioconda
  - r
dependencies:
# needed for single pca plot figures/pca/2d/run0_pc1.png
  - graphviz=2.38.0
  - python=3.5.4
  - snakemake=4.8.1
  - r-data.table=1.11.4
  - r-ggplot2>=2.2.1
  - r-dplyr>=0.7.4
  - shapely=1.5.17
  - fiona=1.7.0 
  - geos=3.4.2 
  - libnetcdf=4.3.3.1
  - kealib=1.4.5
  - descartes=1.1.0

